// swift-tools-version:5.9
// Generated by fastlane :sdk lane — do not edit by hand.
import PackageDescription

let package = Package(
    name: "BidMachinePlus",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "BidMachinePlus", targets: ["BidMachinePlusTarget"])
    ],
    targets: [
        .binaryTarget(
            name: "BidMachinePlus",
            url: "https://bidmachine-ios.s3.amazonaws.com/BidMachinePlus/1.0.0-test.5/package/BidMachinePlus.xcframework.zip",
            checksum: "6967eae79d9cacec3fc466812536599423b83972301388891f1870748f78297f"
        ),
        .binaryTarget(
            name: "BidMachine",
            url: "https://bidmachine-ios.s3.amazonaws.com/BidMachine/3.6.1/package/BidMachine.xcframework.zip",
            checksum: "5959c05caa4e1428e6bad192fc1d87799003faf6d9f1d376729dcc9e61de787b"
        ),
        .binaryTarget(
            name: "OMSDK_Appodeal",
            url: "https://bidmachine-ios.s3.amazonaws.com/OMSDK_Appodeal/1.6.3/package/OMSDK_Appodeal.xcframework.zip",
            checksum: "3e3f791957a55085954608740455c6abad2d1f4381e5a4263242289030f7976f"
        ),
        .binaryTarget(
            name: "Bidon",
            url: "https://bidon-ios.s3.eu-central-1.amazonaws.com/Bidon/0.14.0/Bidon.zip",
            checksum: "07d796da320504322d2d62742ef462d39e6c9e5c6f5fb192422954fff038743d"
        ),
        .binaryTarget(
            name: "BidonAdapterBidMachine",
            url: "https://bidon-ios.s3.eu-central-1.amazonaws.com/BidonAdapterBidMachine/3.6.1.1/BidonAdapterBidMachine.zip",
            checksum: "1a511b23ff834ee57b8e214febbfd4d2b2ba4418bf2dac1a4eb3a584b2a24865"
        ),
        .target(
            name: "BidMachinePlusTarget",
            dependencies: [
                "BidMachinePlus",
                "BidMachine",
                "OMSDK_Appodeal",
                "Bidon",
                "BidonAdapterBidMachine"
            ],
            path: "Sources/BidMachinePlusTarget",
            sources: ["."],
            linkerSettings: [
                .linkedFramework("AdSupport"),
                .linkedFramework("AVFoundation"),
                .linkedFramework("AVKit"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CFNetwork"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("CoreImage"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreTelephony"),
                .linkedFramework("ImageIO"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("SafariServices"),
                .linkedFramework("Security"),
                .linkedFramework("StoreKit"),
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("UIKit"),
                .linkedFramework("WebKit"),
                .linkedFramework("AppTrackingTransparency", .when(platforms: [.iOS])),
                .linkedLibrary("z", .when(platforms: [.iOS])),
                .linkedLibrary("sqlite3", .when(platforms: [.iOS])),
                .linkedLibrary("xml2", .when(platforms: [.iOS]))
            ]
        )
    ]
)
