// swift-tools-version:5.9
// Generated by fastlane :sdk lane — do not edit by hand.
import PackageDescription

let package = Package(
    name: "BidMachinePro",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "BidMachinePro", targets: ["BidMachinePro", "BidMachine", "Bidon", "BidonAdapterBidMachine"])
    ],
    targets: [
        .binaryTarget(
            name: "BidMachinePro",
            url: "https://bidmachine-ios.s3.amazonaws.com/BidMachinePro/1.0.0-test.1/package/BidMachinePro.xcframework.zip",
            checksum: "43c6512e1298a77416e6e76c8be36a49052e0971789d22655202f90ae6545ce6"
        ),
        .binaryTarget(
            name: "BidMachine",
            url: "https://bidmachine-ios.s3.amazonaws.com/BidMachine/3.6.1/package/BidMachine.xcframework.zip",
            checksum: "5959c05caa4e1428e6bad192fc1d87799003faf6d9f1d376729dcc9e61de787b"
        ),
        .binaryTarget(
            name: "Bidon",
            url: "https://bidon-ios.s3.eu-central-1.amazonaws.com/Bidon/0.14.0/Bidon.zip",
            checksum: "07d796da320504322d2d62742ef462d39e6c9e5c6f5fb192422954fff038743d"
        ),
        .binaryTarget(
            name: "BidonAdapterBidMachine",
            url: "https://bidon-ios.s3.eu-central-1.amazonaws.com/BidonAdapterBidMachine/3.6.1.0/BidonAdapterBidMachine.zip",
            checksum: "4873fda43d81cda5e409e8bb3279467dcf76d57bb5c1a8b2f1d3c660030c582d"
        )
    ]
)
